services:
  dealmail:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-runner:latest
    mem_limit: 4g
    restart: always
    environment:
      REPO_URL: "https://github.com/bromanko/dealmail"
      ACCESS_TOKEN: "${ACCESS_TOKEN}" # Sourced from .env file
      RUNNER_LABELS: "self-hosted,docker,mac,nix"
      RUN_AS_ROOT: false
      EPHEMERAL: "true"
      # We’ll manage updates via Docker, not the runner app itself
      DISABLE_AUTO_UPDATE: "true"
